'use client';
import {Component,lazy,Suspense,useEffect,useRef,useState,ReactNode} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
const Scene=lazy(()=>import('./gallery-scene'));
class SceneBoundary extends Component<{children:ReactNode;onError:()=>void},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return{error:true}}componentDidCatch(){this.props.onError()}render(){return this.state.error?null:this.props.children}}
export default function SpatialGallery(){const root=useRef<HTMLDivElement>(null);const progress=useRef(0);const [enabled,setEnabled]=useState(false);const [ready,setReady]=useState(false);const [active,setActive]=useState(true);const [hover,setHover]=useState('');const [mode,setMode]=useState<'space'|'index'>('space');const router=useRouter();
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const small=matchMedia('(max-width: 600px)');const update=()=>{setReady(false);setEnabled(!media.matches&&!small.matches)};update();media.addEventListener('change',update);small.addEventListener('change',update);const observer=new IntersectionObserver(([e])=>setActive(e.isIntersecting),{rootMargin:'100px'});if(root.current)observer.observe(root.current);gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{const intro=root.current?.closest('.hero')?.querySelectorAll('.hero-copy > *');if(!media.matches&&intro?.length){gsap.fromTo(intro,{opacity:0,y:18},{opacity:1,y:0,duration:.85,stagger:.09,ease:'power3.out'});}ScrollTrigger.create({trigger:root.current?.closest('.hero'),start:'top top',end:'bottom top',onUpdate:s=>{progress.current=Math.min(s.progress*1.5,1)}})},root);return()=>{media.removeEventListener('change',update);small.removeEventListener('change',update);observer.disconnect();ctx.revert()}},[]);
 const items=[['ScentSync','/assets/scent-10.webp','/work/project-one-f5w4d-z9nem-s3jda-eyssk-73f62-tmxz9-9jkyc'],['Line Busy','/assets/art-4.webp','/creative-practice'],['REM.log','/assets/rem-2.webp','/work/remlog'],['STEM Math Connections Explorer','/assets/stem-current-home.webp','/work/stem-math-connections-explorer'],['Creative Practice','/assets/home-3.webp','/creative-practice']];
 return <div className={`hero-gallery ${ready&&enabled?'scene-ready':''} ${mode==='index'?'index-mode':''}`} ref={root}><div className="static-gallery">{items.map(([name,src,href],i)=><Link key={name} className={`gallery-link g${i+1}`} href={href} aria-label={`Explore ${name}`} onFocus={()=>setHover(name)} onBlur={()=>setHover('')}><img src={src} alt={name} fetchPriority={i===0?'high':'auto'}/></Link>)}</div>{enabled&&<div className="webgl-gallery"><SceneBoundary onError={()=>{setEnabled(false);setReady(false)}}><Suspense fallback={null}><Scene mode={mode} progress={progress} active={active} onReady={()=>setReady(true)} onHover={setHover} onNavigate={url=>router.push(url)}/></Suspense></SceneBoundary></div>}<div className="gallery-toolbar"><span className="gallery-label" aria-live="polite">{hover||'An open studio, in a little motion.'}</span><div className="view-toggle" aria-label="Gallery layout"><button onClick={()=>setMode('space')} aria-pressed={mode==='space'}>Space</button><button onClick={()=>setMode('index')} aria-pressed={mode==='index'}>Index</button></div></div></div>
}
